# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'Apps', 'verbose_name_plural': 'Apps'},
        ),
        migrations.AddField(
            model_name='app',
            name='url',
            field=models.CharField(default='/party/', max_length=250),
            preserve_default=False,
        ),
    ]
